include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_declorations: false
    avoid_print: false
    use_key_in_widget_constructors: false
    always_use_package_imports: true
